// <auto-generated />
using System;
using FitnessJournal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessJournal.Infrastructure.Migrations
{
    [DbContext(typeof(FitnessJournalContext))]
    [Migration("20240806111528_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessJournal.Domain.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTrackingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTrackingId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("FitnessJournal.Domain.ActivityTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ActivityTrackings");
                });

            modelBuilder.Entity("FitnessJournal.Domain.FitnessInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FitnessLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredWorkoutTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FitnessInformations");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<int?>("FitnessInformationId")
                        .HasColumnType("int");

                    b.Property<string>("GoalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("bit");

                    b.HasKey("GoalId");

                    b.HasIndex("FitnessInformationId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTrackingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rmks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutStats")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTrackingId");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("FitnessJournal.Domain.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTrackingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Duration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("Intensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rmks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTrackingId");

                    b.HasIndex("GoalId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Achievement", b =>
                {
                    b.HasOne("FitnessJournal.Domain.ActivityTracking", null)
                        .WithMany("Achievements")
                        .HasForeignKey("ActivityTrackingId");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Goal", b =>
                {
                    b.HasOne("FitnessJournal.Domain.FitnessInformation", null)
                        .WithMany("Goals")
                        .HasForeignKey("FitnessInformationId");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Progress", b =>
                {
                    b.HasOne("FitnessJournal.Domain.ActivityTracking", null)
                        .WithMany("Progress")
                        .HasForeignKey("ActivityTrackingId");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Workout", b =>
                {
                    b.HasOne("FitnessJournal.Domain.ActivityTracking", null)
                        .WithMany("Workouts")
                        .HasForeignKey("ActivityTrackingId");

                    b.HasOne("FitnessJournal.Domain.Goal", null)
                        .WithMany("Workout")
                        .HasForeignKey("GoalId");
                });

            modelBuilder.Entity("FitnessJournal.Domain.ActivityTracking", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Progress");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitnessJournal.Domain.FitnessInformation", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("FitnessJournal.Domain.Goal", b =>
                {
                    b.Navigation("Workout");
                });
#pragma warning restore 612, 618
        }
    }
}
